edition = "2018"
blank_lines_upper_bound = 2
condense_wildcard_suffixes = true
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
match_arm_leading_pipes = "Preserve"
newline_style = "Unix"
overflow_delimited_expr = true
use_field_init_shorthand = true
wrap_comments = true
use_small_heuristics = "Max"
max_width = 90
