[package]
name = "ast"
version = "0.1.0"
authors = ["Ludwig Stecher <ludwig.stecher@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinystring = { path = "../tinystring" }
thiserror = "1.0"
arbitrary = { version = "0.4.7", features = ["derive_arbitrary"], optional = true }

[features]
fuzz = ["arbitrary"]
